// Guards the visible FAQ (faqHTML) against the static FAQPage JSON-LD in <head>.
// Google only shows FAQ rich results when the schema's questions and answers
// are also visible on the page, so these two must never drift apart.
import { describe, it, expect } from "vitest";
import { HTML } from "./helpers.mjs";

/** Pull the FAQPage block out of the head JSON-LD scripts. */
function faqSchema() {
  const re = /<script type="application\/ld\+json">\s*([\s\S]*?)\s*<\/script>/g;
  let m;
  while ((m = re.exec(HTML))) {
    let json;
    try {
      json = JSON.parse(m[1]);
    } catch {
      continue;
    }
    if (json && json["@type"] === "FAQPage") return json;
  }
  throw new Error("FAQPage JSON-LD not found in index.html");
}

describe("FAQ schema ↔ visible content parity", () => {
  const schema = faqSchema();
  const qa = schema.mainEntity;

  it("has a meaningful set of questions", () => {
    expect(Array.isArray(qa)).toBe(true);
    expect(qa.length).toBeGreaterThanOrEqual(6);
  });

  it("every schema question and answer is also visible on the page", () => {
    // faqHTML() builds the visible section; its English (first L() arg) strings
    // are the canonical copy, so each must appear verbatim in the source.
    for (const entry of qa) {
      expect(entry["@type"]).toBe("Question");
      expect(HTML, `visible FAQ missing question: ${entry.name}`).toContain(entry.name);
      const ans = entry.acceptedAnswer.text;
      expect(HTML, `visible FAQ missing answer: ${ans}`).toContain(ans);
    }
  });

  it("renders one collapsible <details> per question and a container", () => {
    expect(HTML).toContain('id="faqSection"');
    expect(HTML).toContain("function faqHTML(");
    const details = (HTML.match(/<details><summary>\$\{q\}<\/summary>/g) || []).length;
    // The visible list is generated by a single template, so we assert the
    // generator emits a <details> per item rather than counting rendered nodes.
    expect(details).toBe(1);
  });
});
